springProfiles:
  - dev

appName: vas-country-risk-backend
environment: dev

image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

ingress:
  host: catenax-vas-dev.demo.catena-x.net
  enabled: true

certificate:
  host: "vas-country-risk-backend.dev.demo.catena-x.net"

configmap:
  # Specifies whether a configmap should be created or not
  data:
    spring_profiles_active: dev
    APPLICATION_HOST: http://localhost:8080/api/dashboard
    SECURITY_ENABLED: 'true'

applicationSecret:
  enabled: true
  clientSecret: <path:value-added-service/data/country-risk/dev/keycloak#client-secret>
  clientId: <path:value-added-service/data/country-risk/dev/keycloak#client-id>

postgres:
  auth:
    postgresPassword: <path:value-added-service/data/country-risk/dev/postgresql#postgres-password>
    password: <path:value-added-service/data/country-risk/dev/postgresql#password>

pgadmin4:
  enabled: false
  secret:
    path: value-added-service/data/country-risk/dev/pgadmin4
  ingress:
    hosts:
      - host: vas-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - vas-pgadmin4.dev.demo.catena-x.net
        secretName: vas-pgadmin4.dev.demo.catena-x.net-tls