{{- if .Values.applicationSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vas.applicationSecret.name" . }}
type: Opaque
stringData:
  keycloakClientSecret: {{ default (randAlphaNum 15) .Values.applicationSecret.clientSecret }}
  keycloakClientId:  {{ default (randAlphaNum 15) .Values.applicationSecret.clientId }}
{{- end }}