{{- if .Values.applicationSecret.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vas.applicationSecret.name" . }}
type: Opaque
stringData:
  keycloakClientSecret: {{ default {randAlphaNum 10} .Values.applicationSecret.clientSecret }}
  keycloakClientId:  {{ default {randAlphaNum 10} .Values.applicationSecret.clientId }}

{{- end }}